# -*- coding: utf-8 -*-

ColorConfig = {
    "COLOR_VALUES": {
        u"red": u"0,100,100",
        u"darkred": u"0,100,54",
        u"lightcoral": u"0,47,94",
        u"firebrick": u"0,81,71",
        u"brown": u"0,74,65",
        u"indianred": u"0,55,80",
        u"rosybrown": u"0,24,74",
        u"maroon": u"0,100,50",
        u"mistyrose": u"6,12,100",
        u"salmon": u"6,55,98",
        u"tomato": u"9,72,100",
        u"darksalmon": u"15,47,92",
        u"coral": u"16,68,100",
        u"orangered": u"16,100,100",
        u"lightsalmon": u"17,52,100",
        u"sienna": u"19,72,62",
        u"chocolate": u"25,86,82",
        u"saddlebrown": u"25,86,55",
        u"seashell": u"25,6,100",
        u"peachpuff": u"28,28,100",
        u"sandybrown": u"28,60,96",
        u"linen": u"30,8,98",
        u"peru": u"30,69,81",
        u"bisque": u"33,24,100",
        u"darkorange": u"33,100,100",
        u"antiquewhite": u"34,14,98",
        u"tan": u"34,33,83",
        u"burlywood": u"34,39,87",
        u"blanchedalmond": u"36,20,100",
        u"navajowhite": u"36,32,100",
        u"papayawhip": u"37,16,100",
        u"moccasin": u"38,30,100",
        u"oldlace": u"39,9,99",
        u"wheat": u"39,33,99",
        u"orange": u"39,100,100",
        u"floralwhite": u"40,6,100",
        u"goldenrod": u"43,85,85",
        u"darkgoldenrod": u"43,94,72",
        u"cornsilk": u"48,14,100",
        u"gold": u"51,100,100",
        u"khaki": u"54,41,94",
        u"lemonchiffon": u"54,20,100",
        u"palegoldenrod": u"55,29,93",
        u"darkkhaki": u"56,43,74",
        u"beige": u"60,10,96",
        u"lightgoldenrodyellow": u"60,16,98",
        u"ivory": u"60,6,100",
        u"lightyellow": u"60,12,100",
        u"yellow": u"60,100,100",
        u"olive": u"60,100,50",
        u"yellowgreen": u"80,76,81",
        u"olivedrab": u"80,75,56",
        u"darkolivegreen": u"82,56,42",
        u"greenyellow": u"84,82,100",
        u"chartreuse": u"90,100,100",
        u"lawngreen": u"90,100,98",
        u"honeydew": u"120,6,100",
        u"lightgreen": u"120,39,93",
        u"palegreen": u"120,40,99",
        u"darkseagreen": u"120,24,74",
        u"limegreen": u"120,76,81",
        u"lime": u"120,100,100",
        u"forestgreen": u"120,76,55",
        u"green": u"120,100,50",
        u"darkgreen": u"120,100,40",
        u"seagreen": u"146,67,54",
        u"mediumseagreen": u"147,67,71",
        u"mintcream": u"150,4,100",
        u"springgreen": u"150,100,100",
        u"mediumspringgreen": u"157,100,98",
        u"aquamarine": u"160,50,100",
        u"mediumaquamarine": u"160,51,80",
        u"turquoise": u"174,72,88",
        u"lightseagreen": u"177,82,70",
        u"mediumturquoise": u"178,66,82",
        u"azure": u"180,6,100",
        u"lightcyan": u"180,12,100",
        u"paleturquoise": u"180,26,93",
        u"cyan": u"180,100,100",
        u"aqua": u"180,100,100",
        u"darkslategray": u"180,40,31",
        u"darkcyan": u"180,100,54",
        u"teal": u"180,100,50",
        u"darkturquoise": u"181,100,82",
        u"cadetblue": u"182,40,63",
        u"powderblue": u"187,23,90",
        u"deepskyblue": u"195,100,100",
        u"lightblue": u"195,25,90",
        u"skyblue": u"197,42,92",
        u"lightskyblue": u"203,47,98",
        u"steelblue": u"207,61,71",
        u"aliceblue": u"208,6,100",
        u"dodgerblue": u"210,88,100",
        u"lightslategray": u"210,22,60",
        u"slategray": u"210,23,56",
        u"lightsteelblue": u"214,21,87",
        u"cornflowerblue": u"219,58,93",
        u"royalblue": u"225,71,88",
        u"navy": u"240,100,50",
        u"midnightblue": u"240,78,44",
        u"mediumblue": u"240,100,80",
        u"lavender": u"240,8,98",
        u"ghostwhite": u"240,2,100",
        u"blue": u"240,100,100",
        u"darkblue": u"240,100,54",
        u"slateblue": u"248,55,80",
        u"darkslateblue": u"248,56,54",
        u"mediumslateblue": u"249,57,93",
        u"mediumpurple": u"260,49,86",
        u"rebeccapurple": u"270,67,60",
        u"blueviolet": u"271,81,89",
        u"indigo": u"275,100,50",
        u"darkorchid": u"280,76,81",
        u"darkviolet": u"282,100,82",
        u"mediumorchid": u"288,60,83",
        u"thistle": u"300,11,85",
        u"plum": u"300,27,87",
        u"violet": u"300,46,93",
        u"magenta": u"300,100,100",
        u"fuchsia": u"300,100,100",
        u"darkmagenta": u"300,100,54",
        u"purple": u"300,100,50",
        u"orchid": u"302,48,86",
        u"mediumvioletred": u"322,90,78",
        u"deeppink": u"328,92,100",
        u"hotpink": u"330,58,100",
        u"palevioletred": u"340,49,86",
        u"lavenderblush": u"340,6,100",
        u"crimson": u"348,91,86",
        u"pink": u"350,24,100",
        u"lightpink": u"351,28,100",
        u"snow": u"0,2,100",
        u"white": u"360,0,100",
        u"whitesmoke": u"360,0,96",
        u"gainsboro": u"360,0,86",
        u"lightgrey": u"360,0,83",
        u"silver": u"360,0,75",
        u"darkgray": u"360,0,66",
        u"gray": u"360,0,50",
        u"dimgray": u"360,0,41",
        u"black": u"360,NaN,0",
    },
    "COLOR_NAMES": {
        u"rot": u"red",
        u"dunkelrot": u"darkred",
        u"helles korallrot": u"lightcoral",
        u"feuerrot": u"firebrick",
        u"braun": u"brown",
        u"indianerrot": u"indianred",
        u"dunkles rosa": u"rosybrown",
        u"kastanienbraun": u"maroon",
        u"helles rosa": u"mistyrose",
        u"lachsrosa": u"salmon",
        u"tomatenrot": u"tomato",
        u"dunkles lachsrosa": u"darksalmon",
        u"korallenrot": u"coral",
        u"orangerot": u"orangered",
        u"helles lachsrosa": u"lightsalmon",
        u"siennabraun": u"sienna",
        u"schokoladenbraun": u"chocolate",
        u"umbra": u"saddlebrown",
        u"muschelschale": u"seashell",
        u"puder, pfirsichrosa": u"peachpuff",
        u"sandbraun": u"sandybrown",
        u"leinen": u"linen",
        u"braun": u"peru",
        u"biskuit": u"bisque",
        u"dunkles orange": u"darkorange",
        u"altweiß": u"antiquewhite",
        u"hautfarben": u"tan",
        u"blasses orange": u"burlywood",
        u"mandelfarben": u"blanchedalmond",
        u"blasses orangegelb": u"navajowhite",
        u"helles orangegelb": u"papayawhip",
        u"helles orange": u"moccasin",
        u"old lace": u"oldlace",
        u"weizengelb": u"wheat",
        u"orange": u"orange",
        u"blütenweiß": u"floralwhite",
        u"goldrute": u"goldenrod",
        u"dunkle goldrute": u"darkgoldenrod",
        u"helles maisgelb": u"cornsilk",
        u"gold": u"gold",
        u"khaki, erdfarben": u"khaki",
        u"zartes zitronengelb": u"lemonchiffon",
        u"blasse goldrute": u"palegoldenrod",
        u"dunkler erdton": u"darkkhaki",
        u"beige": u"beige",
        u"helles blasses gelb": u"lightgoldenrodyellow",
        u"elfenbein": u"ivory",
        u"hellgelb": u"lightyellow",
        u"gelb": u"yellow",
        u"olive": u"olive",
        u"gelbgrün": u"yellowgreen",
        u"graugrün": u"olivedrab",
        u"dunkles olivegrün": u"darkolivegreen",
        u"grüngelb": u"greenyellow",
        u"chartreuse": u"chartreuse",
        u"grasgrün": u"lawngreen",
        u"honigmelone": u"honeydew",
        u"hellgrün": u"lightgreen",
        u"blasses grün": u"palegreen",
        u"blasses grün": u"darkseagreen",
        u"limonengrün": u"limegreen",
        u"limone": u"lime",
        u"wald grün": u"forestgreen",
        u"grün": u"green",
        u"dunkelgrün": u"darkgreen",
        u"seegrün": u"seagreen",
        u"mittleres seegrün": u"mediumseagreen",
        u"mintgrün": u"mintcream",
        u"frühlingsgrün": u"springgreen",
        u"mittleres frühlingsgrün": u"mediumspringgreen",
        u"aquamarin": u"aquamarine",
        u"mittleres aquamarin": u"mediumaquamarine",
        u"türkis": u"turquoise",
        u"leichtes seegrün": u"lightseagreen",
        u"mittleres türkis": u"mediumturquoise",
        u"himmelblau": u"azure",
        u"helles zyan": u"lightcyan",
        u"blasses türkis": u"paleturquoise",
        u"zyan": u"cyan",
        u"aquamarinblau": u"aqua",
        u"petrol": u"darkslategray",
        u"dunkles zyan": u"darkcyan",
        u"blaugrün": u"teal",
        u"dunkeltürkis": u"darkturquoise",
        u"kadettblau": u"cadetblue",
        u"puderblau": u"powderblue",
        u"tiefes himmelblau": u"deepskyblue",
        u"hellblau": u"lightblue",
        u"himmelblau": u"skyblue",
        u"helles himmelblau": u"lightskyblue",
        u"stahl blau": u"steelblue",
        u"alice blau": u"aliceblue",
        u"dodger blau": u"dodgerblue",
        u"helles schiefer grau": u"lightslategray",
        u"schiefer grau": u"slategray",
        u"helles stahlblau": u"lightsteelblue",
        u"kornblumenblau": u"cornflowerblue",
        u"königsblau": u"royalblue",
        u"marineblau": u"navy",
        u"mitternachtsblau": u"midnightblue",
        u"mittelblau": u"mediumblue",
        u"flieder, fliederblau, lavendel": u"lavender",
        u"weiß mit blaustich": u"ghostwhite",
        u"blau": u"blue",
        u"dunkelblau": u"darkblue",
        u"schlieferblau": u"slateblue",
        u"dunkles schieferblau": u"darkslateblue",
        u"mittleres schieferblau": u"mediumslateblue",
        u"mittleres purpur": u"mediumpurple",
        u"rebecca lila": u"rebeccapurple",
        u"blau violett": u"blueviolet",
        u"indigoblau": u"indigo",
        u"dunkle orchidee": u"darkorchid",
        u"dunkelviolett": u"darkviolet",
        u"mittel orchidee": u"mediumorchid",
        u"distelblau": u"thistle",
        u"pflaumenblau": u"plum",
        u"violett": u"violet",
        u"magenta, fuchsie": u"magenta",
        u"fuchsie, magenta": u"fuchsia",
        u"dunkles magenta": u"darkmagenta",
        u"purpur": u"purple",
        u"helles violett": u"orchid",
        u"violettrot": u"mediumvioletred",
        u"kräftiges pink": u"deeppink",
        u"leuchtendes pink": u"hotpink",
        u"blasses lila": u"palevioletred",
        u"heller fliederton": u"lavenderblush",
        u"purpur": u"crimson",
        u"pink": u"pink",
        u"helles pink": u"lightpink",
        u"weiß mit rotstich": u"snow",
        u"weiß": u"white",
        u"zartes hellgrau": u"whitesmoke",
        u"hellgrau": u"gainsboro",
        u"hellgrau, silbergrau": u"lightgrey",
        u"silber": u"silver",
        u"dunkelgrau": u"darkgray",
        u"grau": u"gray",
        u"dunkelgrau": u"dimgray",
        u"schwarz": u"black",
    }
}
