#!/usr/bin/python3

from flask import Flask, request, make_response
from flask_socketio import SocketIO, emit
from werkzeug.serving import WSGIRequestHandler

import logging
import sys

from datetime import datetime

from smartserver.server import Server

from config import config

from lib.scanner.scanner import Scanner as NetworkScanner
from lib.netflow.processor import Processor as NetflowProcessor
from lib.speedtest.speedtest import Speedtest
from lib.fping.fping import FPing

from lib.mqtt import MQTTHandler
from lib.influxdb import InfluxDB


app = Flask(__name__ )
app.logger = logging.getLogger()
#app.config['SECRET_KEY'] = 'test!'
#socketio = SocketIO(app, async_mode="threading", logger=logging.getLogger(), cors_allowed_origins="*")
socketio = SocketIO(app, async_mode="threading", cors_allowed_origins="*")

class Handler(Server):
    def __init__(self):
        super().__init__("system_service")
        
        #self.startup_timestamp = round(datetime.now().timestamp(),3)
        
        self.mqtt = MQTTHandler(config)
        self.influxdb = InfluxDB(config)
        self.scanner = NetworkScanner(config, self, self.mqtt, self.influxdb )
        self.netflow = NetflowProcessor(config, self, self.influxdb )
        self.speedtest = Speedtest(config, self, self.mqtt, self.influxdb )
        self.fping = FPing(config, self, self.influxdb )

    def start(self, callback):
        self.mqtt.start()
        self.influxdb.start()
        self.scanner.start()
        self.netflow.start()
        self.speedtest.start()
        self.fping.start()

        super().start(callback)

    def terminate(self):
        if self.fping:
            self.fping.terminate()
        if self.speedtest:
            self.speedtest.terminate()
        if self.netflow:
            self.netflow.terminate()
        if self.scanner:
            self.scanner.terminate()
        if self.influxdb:
            self.influxdb.terminate()
        if self.mqtt:
            self.mqtt.terminate()

        super().terminate()
        
    def notifyNetworkData(self, changed_data, msg):
        logging.info("Emit changed network {}".format(msg))

        with app.app_context():
            socketio.emit('network_data', changed_data)
        #socketio.sleep(5)
        
    def emitNetworkData(self):
        [ data, msg ] = self.scanner.getWebSocketData();

        logging.info("Emit initial network {}".format(msg))

        data["root"] = self.scanner.getGatewayMAC()
        emit('network_data', data)

    def notifySpeedtestData(self):
        data = self.speedtest.getWebSocketData();

        logging.info("Emit changed speedtest {}".format(data))

        with app.app_context():
            socketio.emit('speedtest', data)
        #socketio.sleep(5)

    def emitSpeedtestData(self):
        data = self.speedtest.getWebSocketData();

        logging.info("Emit initial speedtest {}".format(data))

        emit('speedtest', data)

    def triggerSpeedtest(self):
        self.speedtest.triggerSpeedtest()

    def getStateMetrics(self):
        scanner_metrics = self.scanner.getStateMetrics()
        netflow_metrics = self.netflow.getStateMetrics()
        speedtest_metrics = self.speedtest.getStateMetrics()
        fping_metrics = self.fping.getStateMetrics()

        influxdb_metrics = self.influxdb.getStateMetrics()
        mqtt_metrics = self.mqtt.getStateMetrics()

        metrics = scanner_metrics + netflow_metrics + speedtest_metrics + fping_metrics + influxdb_metrics + mqtt_metrics
        return "{}\n".format( "\n".join(metrics) )

#@app.route('/state/', methods = ['POST'])
#def state():
#    pass

#https://github.com/miguelgrinberg/Flask-SocketIO/blob/main/example/app.py

@app.route('/metrics/', methods = ['GET'])
def metrics():
    #logging.info(request.headers.get('User-Agent'))
    #return handler.getStateMetrics( "Prometheus" in request.headers.get('User-Agent') )
    return handler.getStateMetrics()

@app.route('/triggerSpeedtest/', methods = ['GET'])
def speedtest():
    #logging.info(request.headers.get('User-Agent'))
    handler.triggerSpeedtest()
    return "ok"

@socketio.on_error_default
def on_error(e):
    logging.error(e)
    sys.excepthook(*sys.exc_info())

@socketio.on('connect')
def on_connect():
    logging.info("on_connect {}".format(request.sid))
    
@socketio.on('disconnect')
def on_disconnect():
    logging.info("on_disconnect {}".format(request.sid))
    
@socketio.on('call')
def on_call(type):
    logging.info("on_call {}".format(type))
    if type == "network_data":
        handler.emitNetworkData()
    elif type == "speedtest":
        handler.emitSpeedtestData()

if __name__ == '__main__':
    Server.initLogger(logging.INFO)

    handler = Handler()

    def handleServer():
        WSGIRequestHandler.protocol_version = "HTTP/1.1"
        socketio.run(app=app, use_reloader=False, host=config.service_ip, port=config.service_port)
        
    handler.start(handleServer)

