#!/bin/sh

IFS=$'\n'

temperatures=$(ls /sys/class/thermal/thermal_zone*/temp 2&>/dev/null)
for item in $temperatures
do
  temperature=$(cat $item)
  sensor=$(echo $item | sed 's/.*thermal_zone\([0-9]\+\).*/\1/')
  printf "zone%s: " $sensor
  echo $temperature | awk '{printf("%.3f\n", $1 / 1000.0)}'
done

temperatures=$(ls /sys/class/ieee80211/phy*/hwmon*/temp1_input 2&>/dev/null)
for item in $temperatures
do
  temperature=$(cat $item)
  sensor=$(echo $item | sed 's/.*hwmon\([0-9]\+\).*/\1/')
  printf "wifi%s: " $sensor
  echo $temperature | awk '{printf("%.3f\n", $1 / 1000.0)}'
done
