#!/usr/bin/python3

import urllib.request
import json

#7.3-fpm
#https://registry.hub.docker.com/api/content/v1/repositories/public/library/php/tags/
#https://registry.hub.docker.com/v2/repositories/library/php/tags/fpm/
#https://registry.hub.docker.com/v2/pgp/tags/list
#https://registry.hub.docker.com/api/content/v1/repositories/public/library/ubuntu/tags?page=${page}&page_size=${size}

REGISTRY="hub.docker.com"
REPOSITORY="php"
CURRENT_VERSION="5.7"

url = "https://{}/v1/repositories/{}/tags".format(REGISTRY,REPOSITORY)

with urllib.request.urlopen(url) as response:
    raw = response.read().decode("utf-8")

    data = json.loads(raw)

print(data)
