- name: set config
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^{{item.field}} '
    line: '{{item.value}}'
    create: '{{is_suse}}'
  with_items:
    - { field: 'PermitRootLogin', value: "PermitRootLogin yes"}
    - { field: 'AuthorizedKeysFile', value: "AuthorizedKeysFile .ssh/authorized_keys" }
    - { field: 'UsePAM', value: "UsePAM yes" }
    - { field: 'Subsystem\s*sftp', value: "Subsystem sftp {{'/usr/libexec/ssh/sftp-server' if is_suse else '/usr/lib/ssh/sftp-server'}}" }
    - { field: 'AllowUsers', value: "AllowUsers *@{{trusted_subnets | join(' *@')}} *@{{vpn_mobile_network}}/24" }
  notify: "restart sshd"

# ***** FINALIZE *****
- name: register service watcher
  vars:
    watcher_name: "{{'ssh' if is_ubuntu else 'sshd'}}"
  include_tasks: roles/systemd_watcher/shared/add_watcher.yml
  tags: ['systemd_watcher_config']
  when: "monitoring_enabled"

- name: trigger sshd handler
  vars:
    notify: "restart sshd"
    service: "{{'ssh' if is_ubuntu else 'sshd'}}"
  include_tasks: roles/_shared/service_check.yml
