#!/bin/sh
{% if "password" in item %}
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]
then
    echo "Please run script as 'source ${BASH_SOURCE[0]}' to set CRYPT ENV VARS correctly"
    exit
fi

read -s -p "Enter password: " PASSWORD
echo ""

PASSWORD=$(/opt/backup_sync/bin/rclone obscure $PASSWORD)

export RCLONE_CONFIG_BACKUP_TYPE="crypt"
export RCLONE_CONFIG_BACKUP_FILENAME_ENCRYPTION="standard"
export RCLONE_CONFIG_BACKUP_DIRECTORY_NAME_ENCRYPTION="true"
export RCLONE_CONFIG_BACKUP_PASSWORD="$PASSWORD"
{% endif %}

read -e -p "Enter destination: " DESTINATION

echo -n "/opt/backup_sync/bin/rclone --links --log-level INFO"

{% if item.destination[0:1] != '/' %}echo -n " --config /opt/backup_sync/config/rclone/{{ item.destination | split(':') | first }}.config"
{% endif %}

{% if "password" in item %}echo " --crypt-remote {{item.destination}}{%if item.sources | selectattr('name', 'defined') | list | length > 0 %}<SUBSDIR>/{% endif %} sync backup: $DESTINATION"
{% else %}echo " sync {{item.destination}}{%if item.sources | selectattr('name', 'defined') | list | length > 0 %}<SUBSDIR>/{% endif %} $DESTINATION"
{% endif %}
