{
 "title": "Solar Waerme",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "Solar Leistung",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "kwatt" }
   ],
   "targets": [
    {
     "alias": "Solarpower",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "pGF_Utilityroom_Heating_Solar_Power_Current_Daily",
     "query": "SELECT last(\"value\") FROM \"pGF_Utilityroom_Heating_Solar_Power_Current_Daily\" WHERE $timeFilter GROUP BY time(1d) fill(none) tz('Europe/Berlin')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Solar Leistung",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "kwatt" }
   ],
   "targets": [
    {
     "alias": "Solarpower",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "pGF_Utilityroom_Heating_Solar_Power_Current_Daily",
     "query": "SELECT last(\"value\") FROM \"pGF_Utilityroom_Heating_Solar_Power_Current_Daily\" WHERE $timeFilter GROUP BY time(1d) fill(none) tz('Europe/Berlin')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Solar Leistung (Aktuell 5 Min)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "kwatt" }
   ],
   "targets": [
    {
     "alias": "Solarpower",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "pGF_Utilityroom_Heating_Solar_Power_Current5Min",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Solarpumpe",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "Solarpumpe",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "pGF_Utilityroom_Heating_Solar_Pump_State",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temperaturen",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "Wasser",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "pGF_Utilityroom_Heating_Temperature_Wather_Storage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    },
    {
     "alias": "Kollektor",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "pGF_Utilityroom_Heating_Temperature_Solar_Collector",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    },
    {
     "alias": "Storage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "pGF_Utilityroom_Heating_Temperature_Solar_Storage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  }
 ]
}