Heating_Temperature_Outdoor|$1|$E1
Heating_Temperature_Outdoor_Subdued|$2|$E2
Heating_Temperature_Offset_Target|$3|$E3
Heating_Temperature_Offset|$4|$E4
Heating_Temperature_Boiler_Target|$5|$E5
Heating_Temperature_Boiler|$6|$E6
Heating_Circuit_Pump_Speed|$7|$E7
Heating_Burner_Starts|$8|$E8
Heating_Burner_Hours|$9|$E9
Heating_Temperature_Wather_Storage|$10|$E10
Heating_Temperature_Solar_Collector|$11|$E11
Heating_Solar_Hours|$12|$E12
Heating_Temperature_Solar_Storage|$13|$E13
Heating_Solar_Power|$14|$E14
Heating_Common_Fault|$15|$E15
Heating_Power|$16|$E16
Heating_Operating_Mode|$17|$E17
Heating_Temperature_Room_Target|$18|$E18
Heating_Solar_Pump_State|$19|$E19
Heating_Solar_Reheating_State|$20|$E20
