{
 "title": "System Info",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "2G",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "alias": "$tag_ip",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "ip" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "network_signal",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "band", "operator": "=", "value": "2g" }
     ]
    }
   ]
  },
  {
   "title": "5G",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "alias": "$tag_ip",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "ip" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "network_signal",
     "query": "SELECT mean(\"value\") FROM \"network_signal\" WHERE (\"band\" = '5g') AND $timeFilter GROUP BY time($__interval), \"ip\" fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "band", "operator": "=", "value": "5g" }
     ]
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "alias": "$tag_ip",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "ip" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "network_total_avg",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}