{
 "title": "System Service WAN",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "TIME",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "speedtest_time",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Speed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Mibits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "DOWN",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "speedtest_downstream_rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "UP",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "speedtest_upstream_rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PING",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "speedtest_ping",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Location",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Mibits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "LOCATION",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "speedtest_location",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "WAN",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Mibits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "WAN TYPE",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "network_wan_type",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "WAN STATE",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "network_wan_state",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "WAN Max Speed",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "alias": "Downstream",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "speedtest_downstream_rate",
     "query": "SELECT max(\"value\")*1024 FROM \"pGF_Corridor_Speedtest_DownstreamRate\" WHERE $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Upstream",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "speedtest_upstream_rate",
     "query": "SELECT max(\"value\")*1024 FROM \"pGF_Corridor_Speedtest_UpstreamRate\" WHERE $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Reachability",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "fping",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Cloud", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Peers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cloud_check_peer_online_state", "legendFormat": "{{peer}}" }
   ]
  },
  {
   "title": "MQTT",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 9, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cloud_check_peer_mqtt_state", "legendFormat": "{{peer}}" }
   ]
  },
  {
   "title": "NFS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cloud_check_peer_mount_state", "legendFormat": "{{peer}}" }
   ]
  },
  {
   "title": "Peer Connections",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cloud_check_topic",
     "legendFormat": "{{source_peer}} => {{target_peer}}"
    }
   ]
  }
 ]
}