{
 "title": "System Service Netflow",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Traffic",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 18, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(src_host) (system_service_netflow_size)",
     "legendFormat": "{{src_host}}"
    }
   ]
  },
  {
   "title": "Protocol",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (protocol) (system_service_netflow_size)",
     "legendFormat": "{{src_host}}"
    }
   ]
  },
  {
   "title": "Sources",
   "type": "table",
   "gridPos": { "h": 13, "w": 5, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (src_host) (system_service_netflow_size)",
     "legendFormat": "{{src_host}}"
    }
   ]
  },
  {
   "title": "Targets",
   "type": "table",
   "gridPos": { "h": 13, "w": 5, "x": 5, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (dest_host) (system_service_netflow_size)",
     "legendFormat": "{{src_host}}"
    }
   ]
  },
  {
   "title": "Services",
   "type": "table",
   "gridPos": { "h": 13, "w": 4, "x": 10, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (service) (system_service_netflow_size)",
     "legendFormat": "{{src_host}}"
    }
   ]
  },
  {
   "title": "Protocol",
   "type": "table",
   "gridPos": { "h": 7, "w": 4, "x": 14, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (protocol) (system_service_netflow_size)",
     "legendFormat": "{{src_host}}"
    }
   ]
  },
  {
   "title": "Services",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 6, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (service) (system_service_netflow_size)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ports",
   "type": "table",
   "gridPos": { "h": 6, "w": 4, "x": 14, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (port) (system_service_netflow_size)",
     "legendFormat": "{{src_host}}"
    }
   ]
  }
 ]
}