{
 "title": "Overview",
 "tags": [ "netflow" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Traffic",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "direction::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "trafficflow",
     "query": "SELECT sum(\"traffic_count\") FROM \"autogen\".\"trafficflow\" WHERE $timeFilter GROUP BY time($__interval), \"direction\"::tag fill(null)",
     "select": [
      [
       { "params": [ "traffic_count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Country",
   "type": "piechart",
   "description": "without speedtest data",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "location_country_name" ], "type": "tag" }
     ],
     "measurement": "trafficflow",
     "query": "SELECT sum(\"value\") FROM \"netflow_size\" WHERE (\"location_org\" =~ /^$Organisation$/ AND \"location_country_name\" =~ /^$Country$/ AND \"service\" =~ /^$Service$/ AND \"intern_host\" =~ /^$InternHost$/ AND \"intern_ip\" =~ /^$InternIP$/ AND \"extern_group\" =~ /^$ExternGroup$/ AND \"extern_host\" =~ /^$ExternHost$/ AND \"extern_ip\" =~ /^$ExternIP$/ AND \"location_country_code\" != 'xx' AND \"service\" != 'speedtest') AND $timeFilter GROUP BY \"location_country_name\"",
     "select": [
      [
       { "params": [ "traffic_size" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "service", "operator": "!=", "value": "speedtest" }
     ]
    }
   ]
  },
  {
   "title": "Service",
   "type": "piechart",
   "description": "without speedtest data",
   "gridPos": { "h": 9, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "service" ], "type": "tag" }
     ],
     "measurement": "trafficflow",
     "select": [
      [
       { "params": [ "traffic_size" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "service", "operator": "!=", "value": "speedtest" }
     ]
    }
   ]
  },
  {
   "title": "Bot & Malwarelists",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_service_blocklists{type=\"entries\"}",
     "legendFormat": "{{listname}}"
    }
   ]
  },
  {
   "title": "Traffic Groups",
   "type": "table",
   "gridPos": { "h": 9, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "group::tag" ], "type": "tag" }
     ],
     "measurement": "trafficflow",
     "select": [
      [
       { "params": [ "traffic_count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Traffic Blocker",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 5 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "extern_ip::tag" ], "type": "tag" },
      { "params": [ "blocking_state::tag" ], "type": "tag" },
      { "params": [ "blocking_reason::tag" ], "type": "tag" }
     ],
     "measurement": "trafficblocker",
     "query": "SELECT last(\"value\") FROM \"autogen\".\"trafficblocker\" WHERE time > now() - 5m GROUP BY \"extern_ip\"::tag, \"blocking_state\"::tag, \"blocking_reason\"::tag, \"blocking_list\"::tag, \"blocking_count\"::tag ORDER BY time DESC",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "extern_ip::tag" ], "type": "tag" }
     ],
     "measurement": "trafficflow",
     "select": [
      [
       { "params": [ "traffic_count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "ip_type" ], "type": "tag" }
     ],
     "measurement": "trafficflow",
     "select": [
      [
       { "params": [ "traffic_size" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Organisations",
   "type": "table",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "location_org" ], "type": "tag" }
     ],
     "measurement": "trafficflow",
     "query": "SELECT sum(\"value\") FROM \"netflow_size\" WHERE (\"location_org\" =~ /^$Organisation$/ AND \"location_country_name\" =~ /^$Country$/ AND \"service\" =~ /^$Service$/ AND \"intern_host\" =~ /^$InternHost$/ AND \"intern_ip\" =~ /^$InternIP$/ AND \"extern_group\" =~ /^$ExternGroup$/ AND \"extern_host\" =~ /^$ExternHost$/ AND \"extern_ip\" =~ /^$ExternIP$/) AND $timeFilter GROUP BY \"location_org\"",
     "select": [
      [
       { "params": [ "traffic_size" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Country",
   "type": "table",
   "gridPos": { "h": 12, "w": 4, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "location_country_name" ], "type": "tag" }
     ],
     "measurement": "trafficflow",
     "query": "SELECT sum(\"value\") FROM \"netflow_size\" WHERE (\"location_org\" =~ /^$Organisation$/ AND \"location_country_name\" =~ /^$Country$/ AND \"service\" =~ /^$Service$/ AND \"intern_host\" =~ /^$InternHost$/ AND \"intern_ip\" =~ /^$InternIP$/ AND \"extern_group\" =~ /^$ExternGroup$/ AND \"extern_host\" =~ /^$ExternHost$/ AND \"extern_ip\" =~ /^$ExternIP$/) AND $timeFilter GROUP BY \"location_country_name\"",
     "select": [
      [
       { "params": [ "traffic_size" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Services",
   "type": "table",
   "gridPos": { "h": 12, "w": 4, "x": 10, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "service" ], "type": "tag" },
      { "params": [ "destination_port::tag" ], "type": "tag" }
     ],
     "measurement": "trafficflow",
     "query": "SELECT sum(\"value\") FROM \"netflow_size\" WHERE (\"location_org\" =~ /^$Organisation$/ AND \"service\" =~ /^$Service$/ AND \"intern_host\" =~ /^$InternHost$/ AND \"intern_ip\" =~ /^$InternIP$/ AND \"extern_group\" =~ /^$ExternGroup$/ AND \"extern_host\" =~ /^$ExternHost$/ AND \"extern_ip\" =~ /^$ExternIP$/ AND \"location_country_name\" =~ /^$Country$/) AND $timeFilter GROUP BY \"service\", \"port\"",
     "select": [
      [
       { "params": [ "traffic_size" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Intern Hosts",
   "type": "table",
   "gridPos": { "h": 12, "w": 5, "x": 14, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "intern_host" ], "type": "tag" }
     ],
     "measurement": "trafficflow",
     "select": [
      [
       { "params": [ "traffic_size" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Extern Hosts",
   "type": "table",
   "gridPos": { "h": 12, "w": 5, "x": 19, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "extern_host" ], "type": "tag" }
     ],
     "measurement": "trafficflow",
     "select": [
      [
       { "params": [ "traffic_size" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  }
 ]
}