{
 "title": "System Service Scanner",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "query": "SHOW TAG VALUES FROM \"network_total_avg\" WITH KEY = \"ip\""
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "2G",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "alias": "$tag_ip",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "ip" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "network_signal",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "band", "operator": "=", "value": "2g" },
      { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "5G",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "alias": "$tag_ip",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "ip" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "network_signal",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "band", "operator": "=", "value": "5g" },
      { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "alias": "$tag_ip",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "ip" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "network_traffic",
     "query": "SELECT sum(\"in_avg\") + sum(\"out_avg\") FROM \"autogen\".\"network_traffic\" WHERE (\"ip\" =~ /^$host$/) AND $timeFilter GROUP BY time(1m), \"ip\" fill(null)",
     "select": [
      [
       { "params": [ "in_avg" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "ip", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  { "title": "Embedded", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Signal (2G & 5G)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "alias": "$tag_band",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "ip" ], "type": "tag" },
      { "params": [ "band" ], "type": "tag" },
      { "params": [ "band" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "network_signal",
     "query": "SELECT mean(\"value\") FROM \"network_signal\" WHERE (\"band\" = '5g') AND $timeFilter GROUP BY time($__interval), \"ip\" fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "alias": "$tag_ip",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "ip" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "network_traffic",
     "query": "SELECT sum(\"in_avg\") + sum(\"out_avg\") FROM \"autogen\".\"network_traffic\" WHERE (\"ip\" =~ /^$host$/) AND $timeFilter GROUP BY time(1m), \"ip\" fill(null)",
     "select": [
      [
       { "params": [ "in_avg" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "ip", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  }
 ]
}