# ***** ENABLE USAGE OF LOCAL DNS *****
- name: "enable : disable systemd-resolved => is_rhel or is_ubuntu"
  systemd:
    state: stopped
    enabled: no
    name: systemd-resolved
  when: "is_rhel or is_ubuntu"

- name: "enable : disable NetworkManager dns handling => is_rhel or is_suse"
  lineinfile:
    path: /etc/NetworkManager/NetworkManager.conf
    insertafter: '^\[main\]'
    regexp: '^{{item.field}}\s*='
    line: '{{item.field}}={{item.value}}'
    create: "{{is_suse}}"
  register: netconfig_status
  with_items:
    - { field: "dns", value: "none" }
  when: "is_rhel or is_suse"

- name: "enable : copy resolv.conf (127.0.0.1)"
  vars:
    local_resolv_server: "127.0.0.1"
  template:
    src: templates/resolv.conf
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: 0755
