#!/usr/bin/python3

import requests
import time
import json

ts = time.time()

try:
    response = requests.get("http://localhost:19999/api/v1/alarms?active&_={}".format(time.time()))
    response.raise_for_status()
except Exception as err:
    print(f"An error happens when fetching alarm states from netdata => {err}")
    print("Maybe netdata is down. Can't inform openhab about system status.")
    exit(1)

data = json.loads(response.content)

level = 0
for name in data['alarms']:
    status = data['alarms'][name]['status']
    if status == "WARNING":
        if level < 1: level = 1
    elif status == "CRITICAL":
        if level < 2: level = 2

try:
    headers = {
        'Accept': 'application/json',
        'Content-Type': 'text/plain'
    }
    response = requests.put( "http://127.0.0.1:8080/rest/items/State_Server/state", headers = headers, data = u"{}".format(level) )
    if not (200 <= response.status_code < 300):
      response.raise_for_status()
except Exception as err:
    print(f"An error happens when reporting alarm state to openhab => {err}")
    exit(1)
