#!/usr/bin/python3

import glob
import os
import sys

if len(sys.argv) != 2:
    print("Missing folder")
    print("Usage: prometheus_generator <yout_prometheus_path>")
    exit(1)

dir_path = sys.argv[1]
tpl_file_path = "{}prometheus.yml.tpl".format(dir_path)
yml_file_path = "{}prometheus.yml".format(dir_path)
#os.path.dirname(os.path.realpath(__file__))

if not os.path.isfile(tpl_file_path):
    print("File '" + tpl_file_path + "' not found")
    exit(1)

with open(tpl_file_path) as f:
    prometheus_yml = f.read()

    rule_files = []
    for file in glob.glob("{}/rules/*.yml".format(dir_path)):
        rule_files.append("  - \"/etc/prometheus/rules/{}\"".format(os.path.basename(file)))

    prometheus_yml = prometheus_yml.replace("{{RULE_FILES}}", "\n".join(rule_files))

    scrape_configs = []
    for file in glob.glob("{}/scrapes/*.yml".format(dir_path)):
        with open(file) as scrape_f:
            for scrape_line in scrape_f:
                scrape_configs.append("  {}".format(scrape_line))
        scrape_configs.append("\n")

    prometheus_yml = prometheus_yml.replace("{{SCRAPE_CONFIGS}}", "".join(scrape_configs))

with open(yml_file_path, "w") as f:
    f.write(prometheus_yml)
    f.close()

st = os.stat(yml_file_path)
os.chown(yml_file_path, st.st_uid, st.st_gid)
