#!/bin/sh /etc/rc.common
# Copyright (C) 2007-2011 OpenWrt.org

USE_PROCD=1
START=50

start_service() {
        mkdir -p /var/empty
        chmod 0755 /var/empty

	procd_open_instance
	procd_set_param command /usr/sbin/fluent-bit -c /etc/config/fluent-bit
	procd_set_param respawn
	procd_close_instance
}
